### ISSUE TITLE
provide fallback for px:asciimathml

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-scripts-utils#69]
It would be useful if a fallback was provided for `px:asciimathml` so that scripts that use it will still run outside of the Pipeline 2 engine (i.e. in oXygen). The fallback could simply be a `p:identity` I suppose.

**Comment by bertfrees** [comment]
OK. But how can we assure that the (Java) step is available in a real production situation. Now, if the step is not available for some reason, it results in a runtime error. If we provide a fallback no error will be thrown, so we have to be notified some other way.

**Comment by josteinaj** [comment]
Right. How about a warning message?

**Comment by bertfrees** [comment]
Yes I thought about that. But it seems a bit weird to show warning messages instead of throwing errors when some step is clearly failing. "Just because" you want it to work in a test environment.

What is the right approach for dealing with these kind of things? The issue actually applies to all the Java steps we have in the Pipeline. Can we guarantee that a Java step gets registered and that otherwise a bundle dependency is not fulfilled? @rdeltour?

**Comment by josteinaj** [comment]
Well, as long as it throws errors, it's pretty cumbersome to develop scripts that use it.

I'm able to do it since I know how to compile and run the dev-launcher, as well as make the dev-launcher listen to script changes (using a script I have that runs mvn install when file changes occur through inotify). Then when the dev-launcher works properly, I either have to run the CLI or fire up a server version of the Web UI to be able to run scripts. I'm able to set this up in a way that gives me a relatively low iteration time between code changes, but I'm not able to run arbitrary XProc scripts in the Pipeline 2 engine (i.e. not Pipeline 2 scripts), which also means no xprocspec tests.

In a production environment I won't mind if it fails, but we can't (and I don't think we should anyway) check in XProc whether or not the environment is in production or development and choose between throwing an error or showing a warning depending on that.

I have all the extension steps defined in calabash set up in my `~/.calabash` so that `px:zip`, `px:copy`, etc. are available when I run scripts in oXygen, but I don't think we can do the same for our own Java-steps?

I think the perfect solution would be to be able to use Pipeline 2 as a XProc engine (including support for XML Catalogs in the file system).

Anyway, just some thoughts...


There could be an option called "fail-if-step-not-available" or the script that invokes the Java step could have a `p:choose` that skips the Java step if it's not available, but neither of those solutions would throw errors in a production environment.

**Comment by bertfrees** [comment]
> Well, as long as it throws errors, it's pretty cumbersome to develop scripts that use it.
> 
> I'm able to do it since I know how to compile and run the dev-launcher, as well as make the dev-launcher listen to script changes (using a script I have that runs mvn install when file changes occur through inotify). Then when the dev-launcher works properly, I either have to run the CLI or fire up a server version of the Web UI to be able to run scripts.

I had a similar setup with dev-launcher before we had XProcSpec. But without the inotify thing, that's pretty smart :) But I hated it because I couldn't do unit testing. It was still very cumbersome.

> I'm able to set this up in a way that gives me a relatively low iteration time between code changes, but I'm not able to run arbitrary XProc scripts in the Pipeline 2 engine (i.e. not Pipeline 2 scripts), which also means no xprocspec tests.

Then when we got XProcSpec I first used my RabbitMQ-based approach for running arbitrary XProc's in the dev-launcher. Later I switched to Pax-Exam, and that works really great for me now.

> In a production environment I won't mind if it fails, but we can't (and I don't think we should anyway) check in XProc whether or not the environment is in production or development and choose between throwing an error or showing a warning depending on that.

No that sounds a bit involved.

> I have all the extension steps defined in calabash set up in my ~/.calabash so that px:zip, px:copy, etc. are available when I run scripts in oXygen, but I don't think we can do the same for our own Java-steps?
> 
> I think the perfect solution would be to be able to use Pipeline 2 as a XProc engine (including support for XML Catalogs in the file system).

That's exactly (well kind of) what I did with my RabbitMQ-based method before and what I am doing now with Pax-Exam. Except for the XML Catalogs part, I don't think the Pipeline supports XML Catalogs in the file system.

But in this particular case, because you basically just want to replace one Java step with the identity step, I think you are far better off with the xproc-maven-plugin, which has support for mocking dependencies now. See https://github.com/daisy/xproc-maven-plugin/issues/9. You can implement px:asciimathml with a simple Java class in src/test/java and a Calabash configuration file in src/test/resources. See https://github.com/daisy/xproc-maven-plugin/tree/master/xproc-maven-plugin/src/it/it-xprocspec-config-calabash for an example.

> Anyway, just some thoughts...
> 
> There could be an option called "fail-if-step-not-available" or the script that invokes the Java step could have a p:choose that skips the Java step if it's not available, but neither of those solutions would throw errors in a production environment.

Indeed. That wouldn't solve anything unless you make that option available as a top-level option. But that sounds a bit involved too.

I'm not against making the step not fail (no need for an option) if that makes your live easier, as long as we can guarantee that it works as expected in an OSGi context (and maybe in addition print a warning).

**Comment by josteinaj** [comment]
> I had a similar setup with dev-launcher before we had XProcSpec. But without the inotify thing, that's pretty smart :) But I hated it because I couldn't do unit testing. It was still very cumbersome.

I have the script as a gist here:
https://gist.github.com/josteinaj/7266810

I have it on my PATH. I have all official Pipeline 2 modules under `~/pipeline-modues` so I just `cd` to that dir and run `autobuild-mvn.sh` to start the autobuild script.

> I'm not against making the step not fail (no need for an option) if that makes your live easier, as long as we can guarantee that it works as expected in an OSGi context (and maybe in addition print a warning).

I'm fine with having a `p:choose` in my script for now until we decide what the best solution is for these cases.

Last time I tried adding support for xprocspec test in the POM of the nordic migrator, I had some trouble with dependencies not being pulled in I think (or something like that). But that's a while ago, I don't remember exactly the problem I had, maybe things have changed since then. I'll have to experiment some more with enabling xprocspec tests in the nordic migrator.

**Comment by bertfrees** [comment]
Yes please give it another try.
 
Last time I heard from you about XProcSpec in the Nordic migrator there was an issue with a NPE, which might be fixed with [this PR](https://github.com/daisy/pipeline-framework/pull/69). This only matters though if you're usubg the Pax-Exam approach. I don't recall an issue with dependencies (that was probably Pax-Exam related too? Maybe [this task](https://github.com/daisy/pipeline-tasks/issues/23) is relevant here?).

**Comment by bertfrees** [comment]
@josteinaj What is the status of this? How are you handling this now? Maybe https://github.com/daisy/pipeline-tasks/issues/29 is the proper solution?

**Comment by josteinaj** [comment]
@bertfrees I think I'm still using a `p:choose` to check for the Java-version of `px:asciimathml`, so I haven't done anything here.

As for using xproc-maven-plugin, I think I'm either waiting for a new xproc-maven-plugin or a new epubcheck to be able to run the tests in the nordic migrator, I don't remember. It's quite limiting not having a working released version of epubcheck so I'm mainly waiting for that.

nlbdev/nordic-epub3-dtbook-migrator#86
nlbdev/nordic-epub3-dtbook-migrator#326
daisy/pipeline-scripts-utils#56

**Comment by bertfrees** [comment]
@josteinaj Status?

**Comment by josteinaj** [comment]
This can be closed. After all the improvements you've made to the build system it's now much easier to import dependencies. We don't need to use the scripts from within oXygen here at NLB either.

**Comment by bertfrees** [comment]
OK cool.
